# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
