# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-11 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuzzyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word_CSV',
            new_name='Word',
        ),
    ]
